.gitignore
README.md
episode-0098/README.md

To start off the episode guide I decided to add the episode 98 show notes from Evernote. I converted this using https://github.com/cs150bf/ever-notedown. I'm not sure if there is a better Evernote -> Markdown converter tool.

Add episode 0098

---

episode-0101/README.md
episode-0104/README.md
episode-0105/README.md
episode-0107/README.md
episode-0108/README.md

My notes are rather terse and tend to be more like keywords to help me track down where I heard/saw something. I also either forget to make notes or haven't finished watching some episodes :)

Add my (incomplete) notes + links for epidodes 101, 104, 105, 107, 108

---

episode-0002/README.md

Initial commit of short description of episode 2 
Could not find the Agenda though.

episode-0002

---

episode-0003/README.md
episode-0004/README.md
episode-0005/README.md
episode-0006/README.md
episode-0007/README.md
episode-0008/README.md

episode-0003+

---

episode-0116/README.md
episode-0117/README.md

Adding the latest and greatest. Thanks for doing this and for being consistent!

Add episode 116 and 117

---

episode-0016/README.md
episode-0079/README.md

Two missing episiodes 16 and 79, the others are not available either on Youtube or Airmoz

TwoMissingEpisodes

---

utils/adso/adso.py

I fixed some small issues while going through this code. You may find it useful

Fix python adso

---

episode-0128/README.md
episode-0129/README.md
episode-0130/README.md
episode-0131/README.md
episode-0132/README.md
episode-0133/README.md
episode-0134/README.md
episode-0135/README.md
episode-0136/README.md

Episode 128 to 136

---

episode-0137/README.md
episode-0138/README.md
episode-0139/README.md

Episodes 137 to 139

---

episode-0140/README.md
episode-0141/README.md

Episodes 140 & 141

---

episode-0142/README.md

new episode + that i saw i had the wrong link for airmo for episode 141

Episode 142 + fix for 141 link to airmo)

---

README.md
episode-0145/README.md

new episode145

---

episode-0145/README.md
episode-0146/README.md

Tried to get episode 145's readme more compact, was so many weird linebreaks earlier... 
thinking of adding a short Contribute.md with some steps i use as a reminder for myself

Episode 146 + some fixups for episode 145

---

CONTRIBUTE.md
README.md
episode-0147/README.md

new Episode + i added a CONTRIBUTE.md, a condensed version of that website on howto create pullrequests (please review :) )

Episode147

---

CONTRIBUTE.md
README.md
episode-0148/README.md

hmm see a '_' snuck in there. maby you can have it removed? 
TODO :_ File a bug for how crazy DevTools was today, graphically.

Episode148

---

README.md
episode-0149/README.md
episode-0150/README.md

You should have ep 149 aswell already committed, allthough, it became 2 commits. Forgot about the index as usual ;)

Episode150

---

README.md
episode-0158/README.md

new ep + hopefully fixed note for Bug1503852. there was a / and | which made the link look wonky

new episode 158 + fix for 157

---

README.md
episode-0162/README.md

new episode 162

---

README.md
episode-0163/README.md
episode-0164/README.md

new episode 163 and 164

---

README.md
episode-0165/README.md

new episode 165

---

README.md
episode-0166/README.md

new episode 166 and added the Notes for Bug 1521964

new episode 166 and fixing missing Notes for 165

---

README.md
episode-0168/README.md

Guess you have to merge in 167 first, or there might be some issues with README.md

new episode 168

---

README.md
episode-0168/README.md
episode-0169/README.md

New episode 169 and i fixed a link in 168 to the Evernote agenda

new episode 169 + fix link in 168

---

README.md
episode-0171/README.md

new episode 171

---

README.md
episode-0172/README.md

new episode 172

---

README.md
episode-0173/README.md

new episode 173

---

README.md
episode-0173/README.md
episode-0174/README.md

new episode 174 and i found i had the wrong link on ep173 for the agenda.

new episode 174 + fixing agenda link for 173

---

README.md
episode-0173/README.md
episode-0174/README.md
episode-0175/README.md

Episode175

---

README.md
episode-0176/README.md

new episode 176

---

README.md
episode-0176/README.md
episode-0177/README.md

new episode 177 + fixing the episode number of the 176 episode

new episode 177 + small fix for 176

---

README.md
episode-0178/README.md

new episode 178

---

README.md
episode-0179/README.md

New episode. 
You might be able to start adding links to the "profile" page of Twitch if you want, using https://help.twitch.tv/s/article/how-to-edit-info-panels?language=en_US

new episode 179

---

README.md
episode-0180/README.md

new episode 180

---

README.md
episode-0181/README.md
episode-0182/README.md

new episodes 181 and 182

---

_episodes/0183/index.md

Im not to good with this git stuff, so maby you can delete my previous pullrequest?

add episode 0183

---

_episodes/0184/index.md

add episode 0184

---

_episodes/0185/index.md

add episode 0185

---

_episodes/0186/index.md

new episode 186
(the airmoz video is named 185, but is actually 186)

add episode 0186

---

_episodes/0186/index.md
_episodes/0187/index.md

Add episode 0187

---

_episodes/0188/index.md

add episode 0188

---

_episodes/0189/index.md

add episode 0189

---

_episodes/0190/index.md

add episode 0190

---

_episodes/0191/index.md

add episode 0191

---

_episodes/0191/index.md
_episodes/0192/index.md

Add episode 0192

---

_episodes/0193/index.md

add episode 0193

---

_episodes/0194/index.md

add episode 0194

---

_episodes/0195/index.md

add episode 0195

---

_episodes/0196/index.md

add episode 0196

---

_episodes/0196/index.md
_episodes/0197/index.md

new episode 197 (also removed "new" from the air mozilla link)

Add episode 0197

---

_episodes/0198/index.md

add episode 0198

---

_episodes/0199/index.md

add episode 0199

---

_episodes/0199/index.md
_episodes/0200/index.md

Add episode 0200

---

_episodes/0201/index.md

add episode 0201

---

_episodes/0202/index.md

new episode 202
(hopefully the year fixes itself in the index, could not really see any place to change that)

add episode 0202

---

_episodes/0203/index.md

add episode 0203

---

_episodes/0203/index.md
_episodes/0204/index.md

Add episode 0204

---

_episodes/0205/index.md

add episode 0205

---

_episodes/0206/index.md

add episode 0206

---

_episodes/0206/index.md
_episodes/0207/index.md

Add episode 0207

---

_episodes/0208/index.md

add episode 0208

---

_episodes/0209/index.md

new episode 209
(hmm lets see if this went well, i was not first able to see this PR on  mikeconley /
joy-of-coding-episode-guide  as i usually can, but had to go to https://github.com/smurfd/joy-of-coding-episode-guide/pull/new/add-episode-0209  for some reason)

add episode 0209

---

_episodes/0210/index.md
_episodes/0211/index.md

add episode 0210 & 0211

---

_episodes/0212/index.md

add episode 0212

---

_episodes/0213/index.md
_episodes/0214/index.md

add episode 0213 & 0214

---

_episodes/0215/index.md

add episode 0215

---

_episodes/0217/index.md
_episodes/0218/index.md

add episode 0217 & 0218

---

_episodes/0217/index.md
_episodes/0218/index.md
_episodes/0219/index.md
_episodes/0220/index.md

Add episode 0219

---

_episodes/0222/index.md

add episode 222

---

_episodes/0223/index.md

add episode 223

---

_episodes/0224/index.md
_episodes/0225/index.md

add episode 224 & 225

---

_episodes/0226/index.md
_episodes/0227/index.md

add episode 226 & 227

---

_episodes/0228/index.md
_episodes/0229/index.md

add episode 228 & 229

---

_episodes/0228/index.md
_episodes/0229/index.md
_episodes/0230/index.md
_episodes/0231/index.md

Add episode 230

---

_episodes/0232/index.md

add episode 232

---

_episodes/0233/index.md
_episodes/0234/index.md

add episode 233 & 234

---

_episodes/0235/index.md

add episode 235

---

_episodes/0236/index.md
_episodes/0237/index.md
_episodes/0238/index.md

add episode 236, 237 & 238

---

_episodes/0239/index.md

add episode 239

---

_episodes/0240/index.md
_episodes/0241/index.md

add episode 240 & 241

---

_episodes/0242/index.md
_episodes/0243/index.md

add episode 242 & 243

---

_episodes/0244/index.md

add episode 244

---

_episodes/0244/index.md
_episodes/0245/index.md

Add episode 245

---

_episodes/0246/index.md

add episode 246

---

_episodes/0247/index.md

add episode 247

---

_episodes/0248/index.md
_episodes/0249/index.md

add episode 248 & 249

---

_episodes/0250/index.md

add episode 250

---

_episodes/0251/index.md

add episode 251

---

_episodes/0252/index.md
_episodes/0253/index.md

add episode 252 & 253

---

_episodes/0254/index.md
_episodes/0255/index.md

add episode 254 & 255

---

_episodes/0256/index.md
_episodes/0257/index.md

add episode 256 & 257

---

_episodes/0258/index.md

add episode 258

---

_episodes/0259/index.md
_episodes/0260/index.md

add episode 259 & 260

---

_episodes/0261/index.md

add episode 261

---

_episodes/0267/index.md
_episodes/0268/index.md

add episode 267 & 268

---

_episodes/0269/index.md
_episodes/0270/index.md

add episode 269 & 270

---

_episodes/0271/index.md
_episodes/0272/index.md

add episodes 271 & 272

---

_episodes/0273/index.md

add episode 273

---

_episodes/0276/index.md

add episode 276

---

_episodes/0277/index.md
_episodes/0278/index.md

add episode 277 & 278

---

_episodes/0279/index.md
_episodes/0280/index.md

add episodes 279 & 280

---

_episodes/0281/index.md
_episodes/0282/index.md
_episodes/0283/index.md

new episodes 281, 282 & 283

---

_episodes/0284/index.md
_episodes/0285/index.md

add episode 284 & 285

---

_episodes/0286/index.md
_episodes/0287/index.md

add episodes 286 & 287

---

_episodes/0290/index.md
_episodes/0291/index.md

add episodes 290 & 291

---

_episodes/0292/index.md
_episodes/0293/index.md

add episodes 292 & 293

---

_episodes/0294/index.md

add episode 294

---

_episodes/0295/index.md
_episodes/0296/index.md

add-episode-295 & 296

---

_episodes/0297/index.md
_episodes/0298/index.md

add episodes 297 & 298

---

_episodes/0299/index.md
_episodes/0300/index.md

add episode 299 & 300

---

_episodes/0301/index.md
_episodes/0302/index.md

add episodes 301 & 302

---

_episodes/0303/index.md
_episodes/0304/index.md

add episode 303 & 304

---

_episodes/0307/index.md
_episodes/0308/index.md

add episode 307 & 308

---

_episodes/0309/index.md

add episode 309

---

_episodes/0310/index.md

add episode 310

---

_episodes/0311/index.md
_episodes/0312/index.md

add episode 311 & 312

---

_episodes/0313/index.md
_episodes/0314/index.md

add episode 313 & 314

---

_episodes/0315/index.md
_episodes/0316/index.md
_episodes/0317/index.md

add episode 315,316 & 317

---

_episodes/0318/index.md

add episode 318

---

_episodes/0319/index.md
_episodes/0320/index.md
_episodes/0321/index.md

new episodes 319, 320 & 321
(episode 319's agenda is a bit messy so i copied it from 318)

add episode 319, 320, 321

---

_episodes/0322/index.md
_episodes/0323/index.md

add episode 322 & 323

---

_episodes/0324/index.md
_episodes/0325/index.md

add episodes 324 & 325

---

_episodes/0326/index.md
_episodes/0327/index.md

add episodes 326 & 327

---

_episodes/0328/index.md
_episodes/0329/index.md

add episode 328

---

_episodes/0330/index.md
_episodes/0331/index.md

add episode 330 & 331

---

_episodes/0333/index.md
_episodes/0334/index.md
_episodes/0335/index.md

add episodes 333, 334 & 335

---

_episodes/0336/index.md
_episodes/0337/index.md
_episodes/0338/index.md

add episodes 336, 337 & 338

---

_episodes/0339/index.md
_episodes/0340/index.md

add episodes 339 & 340

---

_episodes/0341/index.md
_episodes/0342/index.md
_episodes/0343/index.md

add episodes 341, 342 & 343

---

_episodes/0347/index.md

add episode 347

---

_episodes/0348/index.md

new episode 348 (handwritten from the youtube video)

add episode 348

---

_episodes/0351/index.md

add episode 351

---

_episodes/0357/index.md
_episodes/0358/index.md
_episodes/0359/index.md

add episodes 357, 358 & 359

---

_episodes/0360/index.md

add episode 360

---

_episodes/0361/index.md
_episodes/0362/index.md
_episodes/0363/index.md
_episodes/0364/index.md

new episodes 361, 362, 363 & 364

add episodes 361, 362, 363 and 364

---

_episodes/0365/index.md
_episodes/0366/index.md
_episodes/0367/index.md

add episode 365, 366 & 367

---

_episodes/0368/index.md
_episodes/0369/index.md
_episodes/0370/index.md
_episodes/0371/index.md
_episodes/0372/index.md

new episodes 368, 369, 370, 371 & 372

add episodes 368, 369, 370, 371 & 372

---

_episodes/0373/index.md
_episodes/0374/index.md
_episodes/0375/index.md

add episodes 373, 374 & 375

---

_episodes/0376/index.md
_episodes/0377/index.md

add episode 376 & 377

---

_episodes/0381/index.md
_episodes/0382/index.md
_episodes/0383/index.md
_episodes/0384/index.md
_episodes/0385/index.md

new episodes 381, 382, 383, 384 & 385

add episodes 381, 382, 383, 384 & 385

---

_episodes/0386/index.md
_episodes/0387/index.md
_episodes/0388/index.md
_episodes/0389/index.md
_episodes/0390/index.md
_episodes/0391/index.md

new episodes 386, 387, 388, 389, 390 & 391

add episodes 386 to 391

---

_episodes/0392/index.md
_episodes/0393/index.md
_episodes/0394/index.md
_episodes/0395/index.md
_episodes/0396/index.md
_episodes/0397/index.md

new episodes 392, 393, 394, 395, 396 & 397

add episode 392, 393, 394, 395, 396 & 397

---

_episodes/0405/index.md
_episodes/0406/index.md

add episodes 405 & 406
(404 is actually(!) missing from both youtube and agendas, not sure if this was an intentional pun or accidental? :) )

add episodes 405 & 406
